# 1 Load Data

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("../../Data/student_performance_data.csv")
df.drop(columns=['overall_score','student_id'], inplace=True)
df

,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,grade
0,Male,4.54,69.98,36.47,70.70,53.10,17.96,Yes,No,Master,8.09,D
1,Female,5.26,84.80,34.25,27.92,87.17,11.29,No,Yes,Bachelor,4.73,D
2,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,B
3,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,C
4,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,C
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,C
9996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,C
9997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,B
9998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,B
9999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,B

In [2]:
df['grade'].value_counts()

grade
C    5073
B    2704
D    2008
A     154
F      61
Name: count, dtype: int64

In [3]:
df = df[df['grade'].isin(['C','B'])]

,gender,study_hours_per_day,attendance_percentage,assignment_score,midterm_score,final_exam_score,participation_score,internet_access,extra_classes,parent_education,sleep_hours,grade
2,Male,8.69,73.76,72.29,70.92,99.61,76.10,No,Yes,PhD,8.73,B
3,Male,4.06,45.00,97.63,31.73,88.85,33.55,No,No,Bachelor,8.22,C
4,Male,8.83,51.13,65.19,78.28,54.23,88.99,No,No,Bachelor,8.59,C
5,Female,1.79,53.16,33.61,54.26,79.79,58.23,No,No,Bachelor,5.43,C
6,Male,7.99,55.47,45.49,87.83,67.37,53.07,No,Yes,High School,5.68,C
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,6.86,59.65,60.41,39.51,66.43,44.97,Yes,Yes,High School,8.56,C
9996,Male,2.60,83.62,62.45,48.96,81.40,45.11,Yes,Yes,Bachelor,4.21,C
9997,Female,1.46,95.40,67.08,51.51,87.58,65.49,Yes,No,Bachelor,4.72,B
9998,Female,7.15,78.24,97.73,46.51,75.49,61.21,No,No,Bachelor,5.28,B
9999,Male,3.26,97.11,93.33,88.99,85.32,36.14,No,No,Bachelor,8.64,B

In [4]:
df.columns

Index(['gender', 'study_hours_per_day', 'attendance_percentage',
       'assignment_score', 'midterm_score', 'final_exam_score',
       'participation_score', 'internet_access', 'extra_classes',
       'parent_education', 'sleep_hours', 'grade'],
      dtype='str')

##### ohe -> 'gender'
##### ordinal -> 'parent_education'
##### Label -> 'internet_access', 'extra_classes'
##### scaling_transform -> 'study_hours_per_day', 'attendance_percentage','assignment_score', 'participation_score',midterm_score', 'final_exam_score', 'sleep_hours'

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder, StandardScaler, PowerTransformer

scaling_transform = Pipeline([
    ("scl", StandardScaler()),
    ('power', PowerTransformer())
])

preprocessor = ColumnTransformer(transformers=[
    ("ohe", OneHotEncoder(sparse_output=False,handle_unknown='ignore'),['gender']),
    ("ord", OrdinalEncoder(categories=[['High School','Bachelor','Master','PhD']]), ['parent_education']),
    ("ord_bin", OrdinalEncoder(), ['internet_access', 'extra_classes']),
    ("scaling_transform", scaling_transform, ['study_hours_per_day', 'attendance_percentage','assignment_score', 'midterm_score', 'final_exam_score','participation_score', 'sleep_hours'])
    
],remainder='passthrough')

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.2, random_state=42)

In [7]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [8]:
lb = LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [9]:
X_train

array([[ 0.        ,  1.        ,  2.        , ..., -0.71443428,
        -1.00338143,  0.26623556],
       [ 1.        ,  0.        ,  2.        , ..., -1.3161121 ,
        -0.7510872 ,  0.74189396],
       [ 1.        ,  0.        ,  2.        , ..., -1.00509617,
         0.60925752,  0.37632317],
       ...,
       [ 1.        ,  0.        ,  2.        , ...,  1.46435238,
        -0.94723832, -1.29377937],
       [ 1.        ,  0.        ,  1.        , ..., -0.00419386,
        -0.54036775,  0.1082426 ],
       [ 1.        ,  0.        ,  0.        , ...,  0.22430691,
        -0.39103647, -0.540795  ]], shape=(8000, 12))

In [10]:
import torch
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(np.asarray(y_train))   # Series - > Dataframe
y_test = torch.from_numpy(np.asarray(y_test))

# 3. Build Model

In [11]:
import torch.nn as nn
class MySimplePerceptron(nn.Module):
    def __init__(self, X_train):
        super().__init__()
        self.linear = nn.Linear(X_train.shape[1], 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, X_train):
        out = self.linear(X_train)
        return self.sigmoid(out)
    
    def loss_function(self, y_pred, y_train):
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = (  -y_train*torch.log(y_pred) - (1-y_train)*torch.log(1-y_pred) ).mean()
        return loss

# 4. Train Model

In [14]:
def train_model(learning_rate = 0.1,epochs = 100):
    model = MySimplePerceptron(X_train)
    
    for epoch in range(epochs):
        # forward propagation
        y_pred = model.forward(X_train)
        
        # loss calculate
        loss = model.loss_function(y_pred, y_train)
        
        # backpropagation
        loss.backward()
        
        # update weight and bias
        with torch.no_grad():
            model.linear.weight -= (learning_rate * model.linear.weight.grad)
            model.linear.bias -= (learning_rate * model.linear.bias.grad)
            
        # reinitialize gradient
        model.linear.weight.grad.zero_()
        model.linear.bias.grad.zero_()
        
        print(f"Epoch: {epoch+1}, Loss: {loss.item()}")
        
    return model

In [15]:
model = train_model(epochs=100, learning_rate=0.01)

Epoch: 1, Loss: 1.4294708967208862
Epoch: 2, Loss: 1.330317735671997
Epoch: 3, Loss: 1.233304500579834
Epoch: 4, Loss: 1.1384210586547852
Epoch: 5, Loss: 1.0456494092941284
Epoch: 6, Loss: 0.9549660086631775
Epoch: 7, Loss: 0.8663405179977417
Epoch: 8, Loss: 0.7797369360923767
Epoch: 9, Loss: 0.6951145529747009
Epoch: 10, Loss: 0.6124283075332642
Epoch: 11, Loss: 0.5316289663314819
Epoch: 12, Loss: 0.45266425609588623
Epoch: 13, Loss: 0.37547963857650757
Epoch: 14, Loss: 0.30001845955848694
Epoch: 15, Loss: 0.22622261941432953
Epoch: 16, Loss: 0.1540330946445465
Epoch: 17, Loss: 0.08339071273803711
Epoch: 18, Loss: 0.014236039482057095
Epoch: 19, Loss: -0.05348972976207733
Epoch: 20, Loss: -0.11984477937221527
Epoch: 21, Loss: -0.184886634349823
Epoch: 22, Loss: -0.24867096543312073
Epoch: 23, Loss: -0.31125250458717346
Epoch: 24, Loss: -0.3726842403411865
Epoch: 25, Loss: -0.4330175817012787
Epoch: 26, Loss: -0.4923021197319031
Epoch: 27, Loss: -0.5505858063697815
Epoch: 28, Loss: -0.607914388179779
Epoch: 29, Loss: -0.6643322706222534
Epoch: 30, Loss: -0.7198812365531921
Epoch: 31, Loss: -0.7746021747589111
Epoch: 32, Loss: -0.8285334706306458
Epoch: 33, Loss: -0.881712019443512
Epoch: 34, Loss: -0.9341729283332825
Epoch: 35, Loss: -0.9859496355056763
Epoch: 36, Loss: -1.037074089050293
Epoch: 37, Loss: -1.0875765085220337
Epoch: 38, Loss: -1.1374856233596802
Epoch: 39, Loss: -1.18682861328125
Epoch: 40, Loss: -1.2356318235397339
Epoch: 41, Loss: -1.2839196920394897
Epoch: 42, Loss: -1.3317159414291382
Epoch: 43, Loss: -1.3790427446365356
Epoch: 44, Loss: -1.4259207248687744
Epoch: 45, Loss: -1.4723708629608154
Epoch: 46, Loss: -1.5184117555618286
Epoch: 47, Loss: -1.564061164855957
Epoch: 48, Loss: -1.6093367338180542
Epoch: 49, Loss: -1.6542541980743408
Epoch: 50, Loss: -1.6988298892974854
Epoch: 51, Loss: -1.7430779933929443
Epoch: 52, Loss: -1.7870122194290161
Epoch: 53, Loss: -1.8306466341018677
Epoch: 54, Loss: -1.8739933967590332
Epoch: 55, Loss: -1.9170645475387573
Epoch: 56, Loss: -1.959871530532837
Epoch: 57, Loss: -2.002425193786621
Epoch: 58, Loss: -2.044735908508301
Epoch: 59, Loss: -2.0868136882781982
Epoch: 60, Loss: -2.1286675930023193
Epoch: 61, Loss: -2.170306444168091
Epoch: 62, Loss: -2.2117393016815186
Epoch: 63, Loss: -2.252974033355713
Epoch: 64, Loss: -2.294018030166626
Epoch: 65, Loss: -2.334878921508789
Epoch: 66, Loss: -2.3755640983581543
Epoch: 67, Loss: -2.4160797595977783
Epoch: 68, Loss: -2.456432342529297
Epoch: 69, Loss: -2.4966280460357666
Epoch: 70, Loss: -2.536672830581665
Epoch: 71, Loss: -2.5765721797943115
Epoch: 72, Loss: -2.6163313388824463
Epoch: 73, Loss: -2.6559555530548096
Epoch: 74, Loss: -2.6954495906829834
Epoch: 75, Loss: -2.7348179817199707
Epoch: 76, Loss: -2.7740657329559326
Epoch: 77, Loss: -2.8131964206695557
Epoch: 78, Loss: -2.852215051651001
Epoch: 79, Loss: -2.8911242485046387
Epoch: 80, Loss: -2.92992901802063
Epoch: 81, Loss: -2.968632221221924
Epoch: 82, Loss: -3.007237195968628
Epoch: 83, Loss: -3.045748472213745
Epoch: 84, Loss: -3.08416748046875
Epoch: 85, Loss: -3.1224982738494873
Epoch: 86, Loss: -3.160743474960327
Epoch: 87, Loss: -3.1989059448242188
Epoch: 88, Loss: -3.2369890213012695
Epoch: 89, Loss: -3.2749946117401123
Epoch: 90, Loss: -3.312925100326538
Epoch: 91, Loss: -3.350783109664917
Epoch: 92, Loss: -3.388570547103882
Epoch: 93, Loss: -3.426290512084961
Epoch: 94, Loss: -3.4639439582824707
Epoch: 95, Loss: -3.5015339851379395
Epoch: 96, Loss: -3.5390625
Epoch: 97, Loss: -3.5765302181243896
Epoch: 98, Loss: -3.6139402389526367
Epoch: 99, Loss: -3.651293992996216
Epoch: 100, Loss: -3.6885929107666016

# 5. Evaluate Model

In [16]:
def evaluate_model(threshold=0.5):
    with torch.no_grad():  
        y_pred = model.forward(X_test)
        y_pred = (y_pred > threshold).float()
        
        accuracy = (y_test == y_pred).float().mean()
        print(f"Accuracy: {accuracy}")

In [17]:
evaluate_model(threshold=0.5)

Accuracy: 0.27399998903274536