In [1]:
import pandas as pd

df = pd.read_csv("../../../Data/general_knowledge_qa.csv")
df.drop(columns=['question_type','image'],inplace=True)
df

,question,answer
0,How many days do we have in a week?,Seven
1,How many days are there in a normal year?,365 (not a leap year)
2,How many colors are there in a rainbow?,7
3,Which animal is known as the ‘Ship of the Dese...,Camel
4,How many letters are there in the English alph...,26
...,...,...
925,Where are the HeadQuarters of UNESCO?,"Paris, France"
926,Which are the colors of the rings of the Olymp...,"Black, Red, Blue, Green, and Yellow"
927,Who invented ‘Lift’?,Elisha Graves Otis
928,Which river crosses the equator twice?,Congo River
929,Which is the device used to locate submerged o...,SONAR

# 1. Tokenization

In [2]:
def tokenize(text):
    return (text.lower()
            .replace("?","")
            .replace("!","")
            .replace("'","")
            .replace(",","")
            .replace(".","")
            .replace(":","")
            .replace("(","")
            .replace(")","")
            .split())

In [3]:
tokenize("How many days do we have in a week?")

['how', 'many', 'days', 'do', 'we', 'have', 'in', 'a', 'week']

# 2. Build vocab

In [4]:
vocab = {
    "UNK":0
}

In [5]:
def build_vocab(row):
    question_tokens = tokenize(row['question'])
    answer_tokens = tokenize(row['answer'])
    
    merge_tokens = question_tokens + answer_tokens
    
    for token in merge_tokens:
        if token not in vocab:
            vocab[token] = len(vocab)

In [6]:
build_vocab(df.iloc[0,:])
vocab

{'UNK': 0,
 'how': 1,
 'many': 2,
 'days': 3,
 'do': 4,
 'we': 5,
 'have': 6,
 'in': 7,
 'a': 8,
 'week': 9,
 'seven': 10}

In [7]:
df.apply(build_vocab, axis=1)  # every row at a time
print(len(vocab))
vocab

2154

{'UNK': 0,
 'how': 1,
 'many': 2,
 'days': 3,
 'do': 4,
 'we': 5,
 'have': 6,
 'in': 7,
 'a': 8,
 'week': 9,
 'seven': 10,
 'are': 11,
 'there': 12,
 'normal': 13,
 'year': 14,
 '365': 15,
 'not': 16,
 'leap': 17,
 'colors': 18,
 'rainbow': 19,
 '7': 20,
 'which': 21,
 'animal': 22,
 'is': 23,
 'known': 24,
 'as': 25,
 'the': 26,
 '‘ship': 27,
 'of': 28,
 'desert’': 29,
 'camel': 30,
 'letters': 31,
 'english': 32,
 'alphabet': 33,
 '26': 34,
 'consonants': 35,
 '21': 36,
 'sides': 37,
 'triangle': 38,
 'three': 39,
 'month': 40,
 'has': 41,
 'least': 42,
 'number': 43,
 'february': 44,
 'vowels': 45,
 'series': 46,
 'e': 47,
 'i': 48,
 'o': 49,
 'u': 50,
 'called': 51,
 'king': 52,
 'jungle': 53,
 'lion': 54,
 'primary': 55,
 'red': 56,
 'yellow': 57,
 'blue': 58,
 '29': 59,
 'what': 60,
 'you': 61,
 'call': 62,
 'house': 63,
 'made': 64,
 'ice': 65,
 'igloo': 66,
 'largest': 67,
 'world': 68,
 'whale': 69,
 'tallest': 70,
 'on': 71,
 'earth': 72,
 'giraffe': 73,
 'festival': 74,
 'holi': 75,
 'light': 76,
 'diwali': 77,
 'top': 78,
 'color': 79,
 'type': 80,
 'bird': 81,
 'lays': 82,
 'eggs': 83,
 'ostrich': 84,
 '‘festival': 85,
 'flowers’': 86,
 'onam': 87,
 'direction': 88,
 'does': 89,
 'sunrise': 90,
 'east': 91,
 'world’s': 92,
 'flower': 93,
 'rafflesia': 94,
 'zeros': 95,
 'one': 96,
 'hundred': 97,
 'thousand': 98,
 'five': 99,
 'hours': 100,
 'two': 101,
 '48': 102,
 '24+24': 103,
 'months': 104,
 '31': 105,
 'january': 106,
 'march': 107,
 'may': 108,
 'july': 109,
 'august': 110,
 'october': 111,
 'and': 112,
 'december': 113,
 'weeks': 114,
 '52': 115,
 'violet': 116,
 'indigo': 117,
 'green': 118,
 'orange': 119,
 'bones': 120,
 'an': 121,
 'adult': 122,
 'human': 123,
 '206': 124,
 'who': 125,
 'was': 126,
 'first': 127,
 'man': 128,
 'to': 129,
 'walk': 130,
 'moon': 131,
 'neil': 132,
 'armstrong': 133,
 'millimeters': 134,
 '1cm': 135,
 '10': 136,
 'nearest': 137,
 'star': 138,
 'planet': 139,
 'sun': 140,
 'longest': 141,
 'river': 142,
 'nile': 143,
 'principal': 144,
 'source': 145,
 'energy': 146,
 'for': 147,
 'lungs': 148,
 'body': 149,
 'standard': 150,
 'taste': 151,
 'water': 152,
 'tasteless': 153,
 'mountain': 154,
 'mount': 155,
 'everest': 156,
 'fastest': 157,
 'land': 158,
 'cheetah': 159,
 'continent': 160,
 '‘dark’': 161,
 'africa': 162,
 'mars': 163,
 'most': 164,
 'sensitive': 165,
 'organ': 166,
 'our': 167,
 'skin': 168,
 'ocean': 169,
 'pacific': 170,
 'day': 171,
 'observed': 172,
 'environment': 173,
 'june': 174,
 '5': 175,
 'years': 176,
 'century': 177,
 'country': 178,
 'russia': 179,
 'by': 180,
 'area': 181,
 'invented': 182,
 'computer': 183,
 'charles': 184,
 'babbage': 185,
 'players': 186,
 'cricket': 187,
 'team': 188,
 '11': 189,
 'literacy': 190,
 'september': 191,
 '8': 192,
 'inventor': 193,
 'radio': 194,
 'marconi': 195,
 'place': 196,
 'roof': 197,
 'tibet': 198,
 'teeth': 199,
 'healthy': 200,
 'including': 201,
 'wisdom': 202,
 '32': 203,
 'gas': 204,
 'abundant': 205,
 'earth’s': 206,
 'atmosphere': 207,
 'nitrogen': 208,
 'people': 209,
 'over': 210,
 'billion': 211,
 'with': 212,
 'countries': 213,
 'common': 214,
 'non-contagious': 215,
 'disease': 216,
 'tooth': 217,
 'decay': 218,
 'strings': 219,
 'violin': 220,
 'four': 221,
 'planets': 222,
 'solar': 223,
 'system': 224,
 'hottest': 225,
 'smallest': 226,
 'australia': 227,
 'millennium': 228,
 '1000': 229,
 'home': 230,
 'kangaroo': 231,
 'painted': 232,
 'mona': 233,
 'lisa': 234,
 'leonardo': 235,
 'da': 236,
 'vinci': 237,
 'telephone': 238,
 'alexander': 239,
 'graham': 240,
 'bell': 241,
 'internet': 242,
 'prefix': 243,
 'www': 244,
 'stand': 245,
 'wide': 246,
 'web': 247,
 'much': 248,
 'surface': 249,
 'covered': 250,
 '71%': 251,
 'discovered': 252,
 'penicillin': 253,
 '1928': 254,
 'fleming': 255,
 'stars': 256,
 'american': 257,
 'flag': 258,
 '50': 259,
 'shape': 260,
 'that': 261,
 'pentagon': 262,
 'way': 263,
 'anti-clockwise': 264,
 'left': 265,
 'or': 266,
 'right': 267,
 'equal': 268,
 'isosceles': 269,
 '2': 270,
 'coldest': 271,
 'location': 272,
 'antarctica': 273,
 'electricity': 274,
 'benjamin': 275,
 'franklin': 276,
 'widely': 277,
 'spoken': 278,
 'language': 279,
 'mandarin': 280,
 'chinese': 281,
 'parts': 282,
 'continue': 283,
 'grow': 284,
 'your': 285,
 'entire': 286,
 'life': 287,
 'nose': 288,
 'ears': 289,
 '‘democracy’': 290,
 'india': 291,
 'television': 292,
 'john': 293,
 'logie': 294,
 'baird': 295,
 'plateau': 296,
 'tibetan': 297,
 'instrument': 298,
 'used': 299,
 'measure': 300,
 'blood': 301,
 'pressure': 302,
 'sphygmomanometer': 303,
 'symbolizes': 304,
 'peace': 305,
 'white': 306,
 'founder': 307,
 'microsoft': 308,
 'bill': 309,
 'gates': 310,
 'during': 311,
 'did': 312,
 'war': 313,
 'begin': 314,
 '1914': 315,
 'cups': 316,
 'global': 317,
 'warming': 318,
 'caused': 319,
 'excess': 320,
 'carbon': 321,
 'dioxide': 322,
 'cards': 323,
 'complete': 324,
 'pack': 325,
 'name': 326,
 'biggest': 327,
 'rain': 328,
 'forest': 329,
 'amazon': 330,
 'african': 331,
 'nation': 332,
 'famous': 333,
 'chocolate': 334,
 'ghana': 335,
 'makes': 336,
 'up': 337,
 'approx': 338,
 '80%': 339,
 'brain’s': 340,
 'volume': 341,
 'measuring': 342,
 'wind': 343,
 'speed': 344,
 'anemometer': 345,
 '‘stars': 346,
 'stripes’': 347,
 'nickname': 348,
 'united': 349,
 'states': 350,
 'america': 351,
 'process': 352,
 'data': 353,
 'binary': 354,
 'covers': 355,
 'approximately': 356,
 'hardest': 357,
 'substance': 358,
 'available': 359,
 'diamond': 360,
 'desert': 361,
 'sahara': 362,
 'gifted': 363,
 'statue': 364,
 'liberty': 365,
 'france': 366,
 'greek': 367,
 'god': 368,
 'music': 369,
 'apollo': 370,
 '“sim”': 371,
 'sim': 372,
 'card': 373,
 'subscriber': 374,
 'identity': 375,
 'module': 376,
 'element': 377,
 'periodic': 378,
 'table': 379,
 'elements': 380,
 'hydrogen': 381,
 'written': 382,
 'constitution': 383,
 'joint': 384,
 'knee': 385,
 'bone': 386,
 'stapes': 387,
 'ear': 388,
 'atmospheric': 389,
 'barometer': 390,
 'asia': 391,
 'electric': 392,
 'bulb': 393,
 'thomas': 394,
 'alva': 395,
 'edison': 396,
 'whose': 397,
 'memory': 398,
 'nobel': 399,
 'prize': 400,
 'awarded': 401,
 'alfred': 402,
 'woman': 403,
 'go': 404,
 'space': 405,
 'valentina': 406,
 'tereshkova': 407,
 'hcl': 408,
 'hydrochloric': 409,
 'acid': 410,
 'currency': 411,
 'china': 412,
 'renminbi': 413,
 'chameleons': 414,
 'extremely': 415,
 'long': 416,
 'tongues': 417,
 'sometimes': 418,
 'their': 419,
 'bodies': 420,
 'true': 421,
 'false': 422,
 'ostrich’s': 423,
 'eye': 424,
 'bigger': 425,
 'than': 426,
 'its': 427,
 'brain': 428,
 'sneeze': 429,
 'faster': 430,
 'blink': 431,
 'pigs': 432,
 'can': 433,
 'look': 434,
 'into': 435,
 'sky': 436,
 'they': 437,
 'cannot': 438,
 '9': 439,
 'only': 440,
 'planets;': 441,
 'pluto': 442,
 'dwarf': 443,
 'mark': 444,
 'zuckerburg': 445,
 'father': 446,
 'modern': 447,
 'computers': 448,
 'egg': 449,
 'hummingbird': 450,
 'frogs': 451,
 'drink': 452,
 'lots': 453,
 'some': 454,
 'animals': 455,
 'get': 456,
 'sunburn': 457,
 'like': 458,
 'dogs': 459,
 'cats': 460,
 'cows': 461,
 'sunburns': 462,
 'at': 463,
 'tip': 464,
 'noses': 465,
 'william': 466,
 'shakespeare': 467,
 'scientist': 468,
 'he': 469,
 'dramatist': 470,
 'whales': 471,
 'belly': 472,
 'buttons': 473,
 'sharks': 474,
 'blind': 475,
 'mumbai': 476,
 'capital': 477,
 'delhi': 478,
 'camels': 479,
 'store': 480,
 'humps': 481,
 'humans': 482,
 'hearts': 483,
 'heart': 484,
 'chambers': 485,
 'all': 486,
 'tigers': 487,
 'eyes': 488,
 'pediatrician': 489,
 'child': 490,
 'specialist': 491,
 'arachnophobia': 492,
 'fear': 493,
 'it': 494,
 'spiders': 495,
 'dodo': 496,
 'endangered': 497,
 'extinct': 498,
 'bhagat': 499,
 'singh': 500,
 'freedom': 501,
 'fighter': 502,
 'washington': 503,
 'dc': 504,
 'beijing': 505,
 'celebrated': 506,
 'laika': 507,
 'dog': 508,
 'roman': 509,
 'calendar': 510,
 'named': 511,
 'julian': 512,
 '12': 513,
 'ball': 514,
 'bat': 515,
 'stump': 516,
 'hockey': 517,
 'stick': 518,
 'hen': 519,
 'dove': 520,
 'pigeon': 521,
 'cat': 522,
 'hammer': 523,
 'blacksmith': 524,
 'carpenter': 525,
 'cobbler': 526,
 'jeep': 527,
 'car': 528,
 'bike': 529,
 'boat': 530,
 'doctor': 531,
 'surgeon': 532,
 'nurse': 533,
 'teacher': 534,
 'mother': 535,
 'brother': 536,
 'friend': 537,
 'mercury': 538,
 'jupiter': 539,
 'cabbage': 540,
 'potato': 541,
 'capsicum': 542,
 'tomato': 543,
 'pen': 544,
 'pencil': 545,
 'eraser': 546,
 'ink': 547,
 'aeroplane': 548,
 'helicopter': 549,
 'ship': 550,
 'jet': 551,
 'carrot': 552,
 'mango': 553,
 'banana': 554,
 'apple': 555,
 'cow': 556,
 '6': 557,
 'p': 558,
 'j': 559,
 'abdul': 560,
 'kalaam': 561,
 'c': 562,
 'v': 563,
 'raman': 564,
 'issac': 565,
 'newton': 566,
 'dispur': 567,
 'pune': 568,
 'patna': 569,
 'shimla': 570,
 '1': 571,
 '4': 572,
 'europe': 573,
 'loudspeaker': 574,
 'stereo': 575,
 'respiration': 576,
 'digestion': 577,
 'excretion': 578,
 'photosynthesis': 579,
 'hypochlorite': 580,
 'helium': 581,
 'lithium': 582,
 'noun': 583,
 'pronoun': 584,
 'articles': 585,
 'adverb': 586,
 'throat': 587,
 'tongue': 588,
 'coffee': 589,
 'powder': 590,
 'chili': 591,
 'tea': 592,
 'chilli': 593,
 'vitamin': 594,
 'b': 595,
 'd': 596,
 'k': 597,
 'dinosaur': 598,
 'elephant': 599,
 'hippopotamus': 600,
 'where': 601,
 'books': 602,
 'kept': 603,
 'zoo': 604,
 'library': 605,
 'garden': 606,
 'museum': 607,
 'digits': 608,
 'mathematics': 609,
 'infinite': 610,
 'prime': 611,
 'minister': 612,
 'pj': 613,
 'jawaharlal': 614,
 'nehru': 615,
 'indira': 616,
 'gandhi': 617,
 'narendra': 618,
 'modi': 619,
 'bananas': 620,
 'will': 621,
 'be': 622,
 'dozen': 623,
 'd12': 624,
 'mickey': 625,
 'mouse': 626,
 'actor': 627,
 'cartoon': 628,
 'character': 629,
 'author': 630,
 '“god': 631,
 'small': 632,
 'things”': 633,
 'gabriel': 634,
 'garcia': 635,
 'marquez': 636,
 'aravind': 637,
 'adiga': 638,
 'arundhati': 639,
 'roy': 640,
 'victor': 641,
 'hugo': 642,
 'value': 643,
 'pie': 644,
 '14': 645,
 '916': 646,
 '13': 647,
 '34': 648,
 '314': 649,
 '22/7': 650,
 'position': 651,
 'second': 652,
 'third': 653,
 'fourth': 654,
 'aasia': 655,
 'wonders': 656,
 'six': 657,
 'eight': 658,
 'nine': 659,
 'found': 660,
 'concept': 661,
 '“gravitation”': 662,
 'time': 663,
 'albert': 664,
 'einstein': 665,
 'darwin': 666,
 '“julius': 667,
 'caesar”': 668,
 'geoffrey': 669,
 'chaucer': 670,
 'milton': 671,
 'sylvia': 672,
 'plath': 673,
 'when': 674,
 'un': 675,
 '24': 676,
 'constellations': 677,
 'group': 678,
 'galaxies': 679,
 'meteors': 680,
 '“the': 681,
 'planet”': 682,
 'venus': 683,
 'uranus': 684,
 'person': 685,
 'compiles': 686,
 'dictionary': 687,
 'lexicographer': 688,
 'editor': 689,
 'compiler': 690,
 'director': 691,
 'driver': 692,
 'train': 693,
 'pilot': 694,
 'locopilot': 695,
 'captain': 696,
 'full': 697,
 'form': 698,
 'rbi': 699,
 'reputed': 700,
 'bank': 701,
 'reserve': 702,
 'recovery': 703,
 'reduced': 704,
 '“fear': 705,
 'darkness”': 706,
 'nyctophobia': 707,
 'ablutophobia': 708,
 'ophidiophobia': 709,
 'city': 710,
 'peru': 711,
 'lima': 712,
 'rome': 713,
 'los': 714,
 'angeles': 715,
 'prague': 716,
 '27': 717,
 '28': 718,
 '30': 719,
 'wright': 720,
 'brothers': 721,
 'steve': 722,
 'waugh': 723,
 'stephen': 724,
 'hawking': 725,
 'universal': 726,
 'symbol': 727,
 'peacock': 728,
 'pelican': 729,
 'causes': 730,
 'anemia': 731,
 'deficiency': 732,
 'iron': 733,
 'iodine': 734,
 'calcium': 735,
 '“chef”': 736,
 'drives': 737,
 'cooks': 738,
 'food': 739,
 'acts': 740,
 'treats': 741,
 'patients': 742,
 'job': 743,
 'sick': 744,
 'comes': 745,
 'after': 746,
 'before': 747,
 'fish': 748,
 'live': 749,
 'big': 750,
 'fire': 751,
 'virat': 752,
 'kohli': 753,
 'indian': 754,
 'cricketer': 755,
 'young': 756,
 'kitten': 757,
 'national': 758,
 'game': 759,
 'tv': 760,
 'solve': 761,
 '27*0': 762,
 'zero': 763,
 'any': 764,
 'multiplied': 765,
 'gives': 766,
 'answer': 767,
 'give': 768,
 'us': 769,
 'milk': 770,
 'goat': 771,
 'buffalo': 772,
 'den': 773,
 'deposit': 774,
 'money': 775,
 'covid-19': 776,
 'deadly': 777,
 'spread': 778,
 'across': 779,
 '2019': 780,
 '2020': 781,
 'beri-beri': 782,
 'due': 783,
 'coconut': 784,
 'from': 785,
 'tree': 786,
 'state': 787,
 '“god’s': 788,
 'own': 789,
 'country”': 790,
 'kerala': 791,
 'plants': 792,
 'make': 793,
 'through': 794,
 '“land': 795,
 'elephants”': 796,
 'thailand': 797,
 'each': 798,
 'side': 799,
 'basket': 800,
 'commonwealth': 801,
 'games': 802,
 'held': 803,
 'every': 804,
 '_': 805,
 'grand': 806,
 'slam': 807,
 'tennis': 808,
 'tournaments': 809,
 'sports': 810,
 'term': 811,
 'hat-trick': 812,
 'kho': 813,
 'eden': 814,
 'gardens': 815,
 'stadium': 816,
 '–': 817,
 'calcutta': 818,
 'host': 819,
 'cup': 820,
 'england': 821,
 'football': 822,
 'introduced': 823,
 'competitive': 824,
 'olympics': 825,
 '1908': 826,
 'pakistan': 827,
 'sport': 828,
 'canada': 829,
 'lacrosse/ice': 830,
 's': 831,
 'jamaica': 832,
 'turkey': 833,
 'wrestling': 834,
 'were': 835,
 '2010': 836,
 'hosted': 837,
 'maximum': 838,
 'times': 839,
 'caddie': 840,
 'related': 841,
 '__________': 842,
 'golf': 843,
 'olympic': 844,
 'cancelled': 845,
 'because': 846,
 '1916': 847,
 'winner': 848,
 'spain': 849,
 'badminton': 850,
 'originate': 851,
 '22': 852,
 'women’s': 853,
 'men’s': 854,
 'doubles': 855,
 'wimbledon': 856,
 '1884': 857,
 'among': 858,
 'following': 859,
 '“flying': 860,
 'sikh': 861,
 'india”': 862,
 'milkha': 863,
 'total': 864,
 'medals': 865,
 'won': 866,
 '2012': 867,
 'prix': 868,
 '2011': 869,
 'alice': 870,
 'powell': 871,
 '15': 872,
 '16': 873,
 'colours': 874,
 'use': 875,
 '______': 876,
 'hear': 877,
 'tuesday': 878,
 'wednesday': 879,
 '____': 880,
 'legs': 881,
 'need': 882,
 'breathe': 883,
 'oxygen': 884,
 'november': 885,
 'zeroes': 886,
 'hands': 887,
 'chew': 888,
 'using': 889,
 '____________': 890,
 'sense': 891,
 'smell': 892,
 'part': 893,
 'plant': 894,
 'brown': 895,
 'below': 896,
 'ground': 897,
 'roots': 898,
 'seeds': 899,
 'fruit': 900,
 'soaks': 901,
 'nutrients': 902,
 'soil': 903,
 'root': 904,
 'far': 905,
 'sight': 906,
 'turns': 907,
 'head': 908,
 'round': 909,
 'owl': 910,
 'eats': 911,
 'mice': 912,
 '20': 913,
 'wags': 914,
 'tail': 915,
 'lives': 916,
 'kennel': 917,
 'trunk': 918,
 'likes': 919,
 'honey': 920,
 'bear': 921,
 'cunning': 922,
 'fox': 923,
 'neck': 924,
 'black': 925,
 'stripes': 926,
 'zebra': 927,
 'wool': 928,
 'sheep': 929,
 '_____': 930,
 'island': 931,
 'majuli': 932,
 'assam': 933,
 'pig': 934,
 'sty': 935,
 'greenland': 936,
 'mammal': 937,
 'story': 938,
 'ella': 939,
 'leaves': 940,
 'her': 941,
 'glass': 942,
 'slipper': 943,
 'while': 944,
 'attending': 945,
 'royal': 946,
 'cinderella': 947,
 'fairy': 948,
 'tale': 949,
 'meets': 950,
 'dwarfs': 951,
 'cottage': 952,
 'snow': 953,
 'golden': 954,
 'hair': 955,
 'trapped': 956,
 'tower': 957,
 'rapunzel': 958,
 'poor': 959,
 'thief': 960,
 'magic': 961,
 'lamp': 962,
 'aladdin': 963,
 'bad': 964,
 'wolf': 965,
 'going': 966,
 'visit': 967,
 'grandmother': 968,
 'woods': 969,
 'little': 970,
 'riding': 971,
 'hood': 972,
 'girl': 973,
 'falls': 974,
 'rabbit': 975,
 'hole': 976,
 'goes': 977,
 'fantasy': 978,
 'strange': 979,
 'characters': 980,
 'alice’s': 981,
 'adventures': 982,
 'wonderland': 983,
 'heptagon': 984,
 'shaped': 985,
 'sphere': 986,
 '________': 987,
 'hexagon': 988,
 'ten': 989,
 'decagon': 990,
 'octagon': 991,
 'colour': 992,
 'season': 993,
 'cotton': 994,
 'clothes': 995,
 'summer': 996,
 'cow’s': 997,
 '35': 998,
 '36': 999,
 ...}

# 3. Text to numeric representation

In [8]:
def text_to_numeric_rep(text, vocab):
    numerical_present = []
    for word in tokenize(text):
        if word in vocab:
            numerical_present.append(vocab[word])
        else:
            numerical_present.append(0)
    return numerical_present

In [10]:
text_to_numeric_rep("Which animal is known as the ‘Ship of the Desert?’",vocab)

[21, 22, 23, 24, 25, 26, 27, 28, 26, 29]

# 4. Dataloader

In [12]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomDataset(Dataset):
    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab
    def __len__(self):
        return self.df.shape[0]
    
    def __getitem__(self, index):
        row = self.df.iloc[index]

        numerical_question = text_to_numeric_rep(row['question'], self.vocab)
        numerical_answer = text_to_numeric_rep(row['answer'], self.vocab)
        
        return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [13]:
dataset = CustomDataset(df,vocab)

dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [14]:
for ques, ans in dataloader:
    print(ques)
    print(ans)
    break

tensor([[496,  23, 121, 497,  81, 421, 266, 422]])
tensor([[422, 496,  23, 121, 498,  81]])

# 5. Model Build

In [15]:
import torch.nn as nn
class QuesAnsRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
        self.rnn = nn.RNN(50,64, batch_first=True)
        self.fc = nn.Linear(64, vocab_size)
        
    def forward(self, question):
        embedding_ques = self.embedding(question)
        hidden_output, final_output = self.rnn(embedding_ques)
        return self.fc(final_output.squeeze(0))

# 6. Train Model

In [16]:
learning_rate = 0.001
epochs = 50

In [17]:
model = QuesAnsRNN(len(vocab))

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [18]:
for epoch in range(epochs):
    epochs_loss = 0
    for question, answer in dataloader:
        optimizer.zero_grad()
        
        y_pred = model(question)
        
        loss = criterion(y_pred, answer[:,0])
        
        loss.backward()
        
        optimizer.step()
        
        epochs_loss += loss.item()
        
    avg_epoch_loss = epochs_loss / len(dataloader)
    print(f"Epoch {epoch+1}: Loss {avg_epoch_loss}")

Epoch 1: Loss 7.329386776172987
Epoch 2: Loss 5.480903202231213
Epoch 3: Loss 4.342822493949244
Epoch 4: Loss 3.3745112895324665
Epoch 5: Loss 2.5285463999355993
Epoch 6: Loss 1.8191203835510439
Epoch 7: Loss 1.2674941828133919
Epoch 8: Loss 0.8771150904998023
Epoch 9: Loss 0.6166899949081883
Epoch 10: Loss 0.44575684500097107
Epoch 11: Loss 0.3275779057148924
Epoch 12: Loss 0.25037632546918365
Epoch 13: Loss 0.18397448181840642
Epoch 14: Loss 0.1329133028620153
Epoch 15: Loss 0.09781307408658747
Epoch 16: Loss 0.0710122559342273
Epoch 17: Loss 0.04994654023108543
Epoch 18: Loss 0.04083431987210818
Epoch 19: Loss 0.10746499835588638
Epoch 20: Loss 0.1033110438247702
Epoch 21: Loss 0.036111443005602366
Epoch 22: Loss 0.023334143961991325
Epoch 23: Loss 0.02321074938985847
Epoch 24: Loss 0.018133247635854277
Epoch 25: Loss 0.016820350746314043
Epoch 26: Loss 0.01597066065277754
Epoch 27: Loss 0.015113115249856023
Epoch 28: Loss 0.015447562201484044
Epoch 29: Loss 0.020019990508886643
Epoch 30: Loss 0.1365895545098234
Epoch 31: Loss 0.035599318726763744
Epoch 32: Loss 0.03562002473729511
Epoch 33: Loss 0.022980125329482806
Epoch 34: Loss 0.01540337909091934
Epoch 35: Loss 0.0136418541636641
Epoch 36: Loss 0.014071864655450612
Epoch 37: Loss 0.013365783397088679
Epoch 38: Loss 0.01226139950400192
Epoch 39: Loss 0.012913938527945187
Epoch 40: Loss 0.013555291923830736
Epoch 41: Loss 0.07187328896128042
Epoch 42: Loss 0.07055018303619304
Epoch 43: Loss 0.01977916114631342
Epoch 44: Loss 0.01552775422180461
Epoch 45: Loss 0.013331144103765211
Epoch 46: Loss 0.01217189260734754
Epoch 47: Loss 0.011770854950867042
Epoch 48: Loss 0.012862563934791607
Epoch 49: Loss 0.013039835900563977
Epoch 50: Loss 0.012814538990479837

# 7. Inference

In [33]:
def predict(model, question, threshold=0.5, words=1):
    # convert text to number
    numerical_question = text_to_numeric_rep(question, vocab)
    
    # make it tensor
    tensor_question = torch.tensor(numerical_question).unsqueeze(0)
    
    # probabilities
    output_probability = model(tensor_question)
    
    # use softmax
    probs = torch.nn.functional.softmax(output_probability, dim=1)
    
    # get max probs
    max_prob, max_index = torch.max(probs, dim=1)
    
    inverse_vocab = {value:key for key, value in vocab.items()}
    
    if max_prob >= threshold:
        print(list(vocab.keys())[max_index])
        print(f"Probability: {max_prob}")
    else:
        print("I dont know")
        print(f"Probability: {max_prob}")

In [34]:
predict(model,"How many days are there in a normal year?",words=1, threshold=0.5)

365
Probability: tensor([0.9985], grad_fn=<MaxBackward0>)

In [36]:
predict(model,"Which animal is known as the ‘Ship of the Desert?’",words=1, threshold=0.8)

camel
Probability: tensor([0.9999], grad_fn=<MaxBackward0>)

In [42]:
predict(model,"How many sides are there in a triangle?’",words=1, threshold=0.7)

I dont know
Probability: tensor([0.5207], grad_fn=<MaxBackward0>)

In [20]:
df

,question,answer
0,How many days do we have in a week?,Seven
1,How many days are there in a normal year?,365 (not a leap year)
2,How many colors are there in a rainbow?,7
3,Which animal is known as the ‘Ship of the Dese...,Camel
4,How many letters are there in the English alph...,26
...,...,...
925,Where are the HeadQuarters of UNESCO?,"Paris, France"
926,Which are the colors of the rings of the Olymp...,"Black, Red, Blue, Green, and Yellow"
927,Who invented ‘Lift’?,Elisha Graves Otis
928,Which river crosses the equator twice?,Congo River
929,Which is the device used to locate submerged o...,SONAR